version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t interline-io/planetutils:$CIRCLE_BRANCH .
      - run:
          name: Run tests in container
          command: docker run -it interline-io/planetutils:$CIRCLE_BRANCH python setup.py test
